language: generic 
sudo: required
services:
  - docker

before_install:
  - docker build -t sebabanan/docker-test -f Dockerfile.dev .

script:
  - docker run -e CI=true sebabanan/docker-test npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-test"
  env: "DockerTest-env"
  bucket_name: "elasticbeanstalk-us-east-2-131201257740"
  bucket_path: "docker-test"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"